
listofwindowsapp:
  - name: firstwindowsapp    
    os_type: Windows
    sku_name: P1v2

listofsql_server:
name                          = "sqlserver"
version                       = "12.0"
administrator_login           = "4dm1n157r470r"
administrator_login_password  = "4-v3ry-53cr37-p455w0rd"
