listoflinuxapp:
 - name: firstlinuxapp    
   os_type: Linux
   sku_name: P1v2

listoflinuxapp:
  - name: secondlinuxapp    
    os_type: Linux
    sku_name: P1v2
   
listofwindowsapp:
  - name: firstwindowsapp    
    os_type: Windows
    sku_name: P1v2

listofsql_server:
 - name: sqlserver
   version: "12.0"
