listofwindowsapp:
  - name: firstwindowsapp    
    os_type: window
    sku_name: P1v2
  - name: secondwindowsapp    
    os_type: window
    sku_name: P1v2
  - name: thirdwindowsapp    
    os_type: window
    sku_name: P1v2
